language: node_js
node_js:
  - "10"
cache:
  directories:
  - node_modules
script:
  - npm run lint
  - npm run build
  - npm run build:demo:client
  - npm run test
notifications:
  webhooks: https://coveralls.io/webhook
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: dist/demo/browser
  on:
    branch: master